services:
  - type: web
    name: filebin
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: filebin-db
          property: connectionString
    domains:
      - filebin.yourdomain.com

databases:
  - name: filebin-db
    plan: starter